services:
  api:
    container_name: compras
    hostname: compras
    restart: unless-stopped

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3012:8080"

    environment:
      - NODE_ENV=production        
    env_file:
      - .env  # ‚Üê ADICIONE ESTA LINHA
    networks:
      - docker-server

networks:
  docker-server:
    external: true
